language: php
php:
    - 5.4
    - hhvm

matrix:
    allow_failures:
        - php: hhvm
        
before_script:
    - composer self-update
    - composer install --dev --prefer-dist
    - chmod +x bin/execute_tests_paratest.sh
    #- "wget http://chromedriver.storage.googleapis.com/2.9/chromedriver_linux32.zip && unzip chromedriver_linux32.zip"
    - "sh -e /etc/init.d/xvfb start"
    - "export DISPLAY=:99.0"
    - "wget http://selenium-release.storage.googleapis.com/2.41/selenium-server-standalone-2.41.0.jar"
    - "java -jar selenium-server-standalone-2.41.0.jar -role hub > /dev/null &"
    - sleep 5
    - "java -jar selenium-server-standalone-2.41.0.jar -role node -hub http://localhost:4444/grid/register -browser browserName=firefox,maxInstances=15,platform=LINUX -port 6667 > /dev/null &"
    - sleep 5

script:
    - export BROWSER=firefox
    - bin/execute_tests_paratest.sh